### ISSUE TITLE
No way to associate an existing payment to a new subscription?

### ISSUE THREAD

**Issue by TomasHurtz** [Prospress/woocommerce-subscriptions-preserve-billing-schedule#1]
Hi - this is useful, but there does not appear to be a way to manually associate an existing payment to a new recurring subscription (that was manually created after payment was received).

There does not appear to be a way to associate an existing payment in the "Related Orders" section in admin "Edit Subscription" page. 

Thanks

**Comment by thenbrent** [comment]
> there does not appear to be a way to manually associate an existing payment to a new recurring subscription (that was manually created after payment was received).

@TomasHurtz that's correct, there is no interface to link an existing order to a subscription. You will need to manually set the post ID of the order in which the existing payment was recorded as the `post_parent` on the `shop_subscription` post type by modifying the database directly.

If you would like an interface for that to be added, please [request it as a feature](http://ideas.woothemes.com/forums/133476-woocommerce).

Alternatively, you can do things in the opposite directly and create an order associated with the subscription using this method: https://docs.woocommerce.com/document/subscriptions/add-or-modify-a-subscription/#section-14

Please note, this question/issue has nothing to do with the plugin in this repository. It's a more general support question for Subscriptions. Please submit questions like that to [WooCommerce.com support](https://woocommerce.com/my-account/create-a-ticket/).
