### ISSUE TITLE
Will this be outdated in case of Subscriptions 2.3?

### ISSUE THREAD

**Issue by ajgw** [Prospress/woocommerce-subscriptions-preserve-billing-schedule#3]
I have read few about the new Subscriptions 2.3 and its new features but did not completely because of my limited english.

Will this extension still needed or will it be outdated in case of Subscriptions 2.3.x?

**Comment by james-allan** [comment]
Hi @ajgw. 

Yes, this extension will still be needed with Subscriptions 2.3 and no, it's not outdated. This means you can and should continue to use it if that's what you have been doing in the past.
