### ISSUE TITLE
Am I correct how it works?

### ISSUE THREAD

**Issue by vnzhlv-zh** [Prospress/woocommerce-subscriptions-preserve-billing-schedule#4]
Hello,
This question just to clarify how it works.

For example, we have a monthly subscription. 
If the product is purchased on the 1st of January, the next renewal payment day should be on the 1st of February. Customer manually pays for the renewal on the 3rd of February. So the next payment date will be the 1st of March, is it correct? If so, what happens with the subscription status between 1st of February and 3rd of February? 

Thanks

**Comment by thenbrent** [comment]
That's correct @vanzhilov. :)

> If so, what happens with the subscription status between 1st of February and 3rd of February?

It will be _on-hold_ still, the standard status applied between [when the renewal is due and when payment is processed](https://docs.woocommerce.com/document/subscriptions/renewal-process/#section-5). This plugin doesn't change that.

**Comment by vnzhlv-zh** [comment]
@thenbrent Thank you very much for the quick response! ^_^
Another example. What if the customer pays on the 5th of July for example? So, he didn't pay for 6 months.
