### ISSUE TITLE
Early renewal

### ISSUE THREAD

**Issue by levikapitany** [Prospress/woocommerce-subscriptions-preserve-billing-schedule#5]
Hi,

Just interested to see what happens if the customer renews early? E.g if the subscribed on June 1 2018, but renews on May 1 2019.
Will their subscription end date change to May 1 2020, or June 1 2020?
It would be great if the customer could renew early and keep the 13 month susbcription.

Thanks,
Levi

**Comment by thenbrent** [comment]
Hi @levikapitany good question.

> Will their subscription end date change to May 1 2020, or June 1 2020?

The end date will be June 1 2020.

I've just added a new section to the README.me to document how the plugin functions with an early renewal: https://github.com/Prospress/woocommerce-subscriptions-preserve-billing-schedule#early-renewal-calculations
