### ISSUE TITLE
Fatal error on get_coupon_codes()

### ISSUE THREAD

**Issue by m-phil** [Prospress/woocommerce-subscriptions-preserve-billing-schedule#7]
class WC_Subscriptions_Coupon:
The functions order_has_limited_recurring_coupon() and check_coupon_usages() using
$coupons = WC_Abstract_Order::get_coupon_codes() 
but it occurs an 
PHP Fatal error:  Uncaught Error: Using $this when not in object context in 
/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php:830
i.e. immedatly after getting back from a payment process like PayPal.

To fix it replace it with
$order = new WC_Order();
$coupons = $order->get_coupon_codes();

**Comment by james-allan** [comment]
@m-phil The error you mentioned isn't related to this plugin. It relates to the core WooCommerce Subscriptions plugin. 

I've had a look at the specific error you mentioned and it has been fixed for quite some time now. Please check you have the latest version of WooCommerce Subscriptions. The latest version is 2.6.5. 

Finally, this isn't the right place to get support for errors like this. In future please contact WooCommerce support via your WooCommerce.com account page.
