### ISSUE TITLE
Is this compatible with WooCommerce Subscriptions version 3 or above?

### ISSUE THREAD

**Issue by philmatthews** [Prospress/woocommerce-subscriptions-preserve-billing-schedule#8]
Do you know if this plugin works with the new version 3 (or higher) of WooCommerce Subscriptions? Thanks, Phil

**Comment by thenbrent** [comment]
@philmatthews yes it will work with Subscriptions 3.0.

FWIW, Subscriptions 3.0 had very few breaking changes. The primary reason a major version number was used is because it moved critical data to a new database tables, rather than being a large rewrite of the code. Hope that helps. :)
